name: Tests

on:
  push:
  pull_request:

jobs:
  vitest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        run: yarn install --non-interactive

      - name: Run Tests
        run: yarn test:run
